<?php

namespace ripnet\EvoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ROMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ROMRepository extends EntityRepository
{
    public function getParents()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r, c FROM ripnetEvoBundle:ROM r JOIN r.children c')
            ->getResult();
    }
}
